controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_base_1_joint
      - left_1_2_joint
      - left_2_3_joint
      - left_3_4_joint
  - name: fake_right_arm_controller
    joints:
      - right_base_1_joint
      - right_1_2_joint
      - right_2_3_joint
      - right_3_4_joint
initial:  # Define initial robot poses.
  - group: left_arm
    pose: home_left
  - group: right_arm
    pose: home_right